/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Browse: typeof import('./src/components/Browse.vue')['default']
    Guided: typeof import('./src/components/Guided.vue')['default']
    PatternBrowser: typeof import('./src/components/PatternBrowser.vue')['default']
    PatternCard: typeof import('./src/components/PatternCard.vue')['default']
    PatternChapter: typeof import('./src/components/PatternChapter.vue')['default']
    PatternPreviewCard: typeof import('./src/components/PatternPreviewCard.vue')['default']
  }
}
